"""add slug column in work model

Revision ID: 52ef88ea4bc6
Revises: 197e31529d00
Create Date: 2025-01-07 17:47:19.763066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ef88ea4bc6'
down_revision = '197e31529d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.create_unique_constraint('slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_constraint('slug', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
