"""add project url and repository url to work model

Revision ID: b3bfea9c1dfd
Revises: e9688b1e1c5d
Create Date: 2024-12-03 22:22:36.017020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bfea9c1dfd'
down_revision = 'e9688b1e1c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('repository_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('repository_url')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
